---
engines:
  markdownlint:
    enabled: true
  vint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.sh"
  - "**.vim"
exclude_paths:
  - vim/.vim/colors/
  
#comment to test
